"""Generate docs/METRIC_DICTIONARY.md from the Cube YAML model (the single source of truth for definitions)."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = ROOT / "cube" / "model" / "cubes"
OUT = ROOT / "docs" / "METRIC_DICTIONARY.md"
REQUIRED_META = ("owner", "formula", "time_semantics", "unit", "source_tables")
SEMANTICS = {
    "flow": "summed over the period",
    "period_end": "value at the last month end of the period",
    "average": "mean of the monthly values in the period",
}


def load_metrics() -> list[dict]:
    metrics = []
    for path in sorted(MODEL_DIR.glob("*.yml")):
        for cube in yaml.safe_load(path.read_text(encoding="utf-8"))["cubes"]:
            dims = [d["name"] for d in cube.get("dimensions", [])
                    if d.get("public", True) and not d.get("meta", {}).get("internal")]
            for m in cube.get("measures", []):
                metrics.append({**m, "cube": cube["name"], "dimensions": dims})
    return metrics


def render(metrics: list[dict]) -> str:
    lines = [
        "# Metric Dictionary",
        "",
        "Generated by `python scripts/build_metric_dictionary.py` from `cube/model/cubes/*.yml`. Do not edit by hand.",
        "",
        "**Business date = posting date** for transactions; snapshot cubes use month end; campaigns use the month the "
        "campaign started. Segment and branch are always as of the business date (SCD Type 2).",
        "",
        "Time semantics: " + "; ".join(f"`{k}` = {v}" for k, v in SEMANTICS.items()) + ".",
        "",
    ]
    for cube in dict.fromkeys(m["cube"] for m in metrics):
        lines += [f"## {cube}", ""]
        for m in (x for x in metrics if x["cube"] == cube and x["meta"].get("catalog", True)):
            meta = m["meta"]
            lines += [
                f"### `{m['name']}` - {m['title']}",
                "",
                m["description"].strip(),
                "",
                f"* **Formula:** {meta['formula']}",
                f"* **Owner:** {meta['owner']}",
                f"* **Time semantics:** `{meta['time_semantics']}` ({SEMANTICS[meta['time_semantics']]})",
                f"* **Unit:** {meta['unit']}",
                f"* **Source tables:** {', '.join(meta['source_tables'])}",
                f"* **Dimensions:** {', '.join(m['dimensions'])}",
            ]
            if meta.get("caveats"):
                lines.append(f"* **Caveats:** {meta['caveats']}")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(render(load_metrics()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
