"""Demo step 1: the same question answered three ways. Writes docs/CONFLICTING_REPORTS.md from the raw data.

Two plausible departmental reports disagree; the governed metric (one definition, one owner) is the tie-breaker.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from story_checks import churn_by_month, load_all, segment_asof

OUT = Path(__file__).resolve().parents[1] / "docs" / "CONFLICTING_REPORTS.md"
ME = pd.Timestamp("2026-09-30")
Q3_START = pd.Timestamp("2026-07-01")


def main() -> None:
    t = load_all()
    c, tx = t["customers"], t["transactions"]
    alive = c[(c.acquisition_date <= ME) & (c.churn_date.isna() | (c.churn_date > ME))]

    active_30 = alive.customer_id.isin(tx[(tx.posting_date > ME - pd.Timedelta(days=30)) & (tx.posting_date <= ME)].customer_id)
    active_90 = alive.customer_id.isin(tx[(tx.posting_date > ME - pd.Timedelta(days=90)) & (tx.posting_date <= ME)].customer_id)

    attrs_end = segment_asof(t, alive.customer_id, ME)
    yp_end = int((attrs_end.segment == "Young Professionals").sum())
    yp_all = churn_by_month(t, "Young Professionals")
    q3 = yp_all[(yp_all.month_end >= Q3_START) & (yp_all.month_end <= ME)]
    churned = int(q3.churned.sum())
    opening_start = int(q3.opening.iloc[0])

    rows_active = [
        ("Marketing deck", "Customers with a transaction in the last 30 days", f"{int(active_30.sum()):,}"),
        ("Branch operations", "Customers with an open relationship (not churned)", f"{len(alive):,}"),
        ("**Governed `active_customers`**", "Customers with a transaction in the 90 days to period end", f"**{int(active_90.sum()):,}**"),
    ]
    rows_churn = [
        ("Marketing deck", "Q3 churned / customers at the END of Q3", f"{churned / yp_end:.2%} ({churned:,} / {yp_end:,})"),
        ("Finance pack", "Q3 churned / customers at the START of Q3", f"{churned / opening_start:.2%} ({churned:,} / {opening_start:,})"),
        ("**Governed `churn_rate`**", "Churned / sum of monthly opening customers (a monthly rate)",
         f"**{churned / int(q3.opening.sum()):.2%}**"),
    ]

    def table(rows: list[tuple[str, str, str]]) -> str:
        head = "| Report | Definition used | Reported value |\n|---|---|---|\n"
        return head + "\n".join(f"| {a} | {b} | {c} |" for a, b, c in rows)

    OUT.write_text(f"""# One question, three answers

Generated by `python scripts/conflicting_reports.py` from the synthetic data (reference date 2026-09-30).
Nobody in these examples made an error: each report applied a reasonable but *different* definition.

## "How many active customers do we have?"

{table(rows_active)}

## "What was Young Professionals churn in Q3 2026?"

{table(rows_churn)}

**Talking point:** every figure above is correct for its own definition, which is exactly why committees argue.
In this system a metric has a single definition, an owner, a formula and a source, so the copilot, the dashboard and
any external MCP client return the same number and can show the definition beside it (Trust center -> Metric dictionary).
""", encoding="utf-8")
    print(f"wrote {OUT}")
    print(table(rows_active))
    print(table(rows_churn))


if __name__ == "__main__":
    main()
