"""Print the data-quality report and planted-story figures. Optionally write docs/STORIES.md."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from story_checks import load_all, quality_report, story_figures

DOCS = Path(__file__).resolve().parents[1] / "docs"


def render_stories(fig: dict) -> str:
    camp = fig["d_campaigns"]
    best = camp.loc[camp.cac.idxmin()]
    worst = camp.loc[camp.loc[camp.response_rate >= camp.response_rate.quantile(0.9)].conversion_rate.idxmin()]
    first_cross = fig["e_first_month_mobile_exceeds_atm"]
    m0, a0, m1, a1 = fig["e_mobile_atm_first_last"]
    table = camp.assign(
        response_rate=lambda d: (d.response_rate * 100).round(1).astype(str) + "%",
        conversion_rate=lambda d: (d.conversion_rate * 100).round(1).astype(str) + "%",
        cac=lambda d: d.cac.round(0).astype(int),
        cost=lambda d: d.cost.astype(int),
    ).to_markdown(index=False)
    return f"""# Planted Stories (seed 42, window {fig['months']})

Generated by `python scripts/data_quality_report.py --write-docs` from the raw CSVs with pandas only.
Figures are exact for the committed seed and reference date; the Cube golden tests must reproduce them.

## a) Young Professionals churn rises sharply in the last quarter
* Average monthly churn, last quarter: **{fig['a_yp_churn_last_quarter_avg_monthly']:.2%}**
* Average monthly churn, prior 21 months: **{fig['a_yp_churn_prior_21m_avg_monthly']:.2%}**
* Bank-wide last quarter (all segments): {fig['a_bank_churn_last_quarter_avg_monthly']:.2%}
* Monthly YP churn, last six months: {fig['a_yp_churn_by_month_last6']}

## b) RMG supply-chain NPL rises in Narayanganj and Gazipur
* NPL ratio of the RMG / Garments SME loans in the two branches: **{fig['b_stress_npl_ratio_first']:.1%}** -> **{fig['b_stress_npl_ratio_last']:.1%}**
* Rest of the loan book: {fig['b_rest_npl_ratio_first']:.1%} -> {fig['b_rest_npl_ratio_last']:.1%}

## c) CASA ratio declines as fixed deposits grow
* CASA ratio: **{fig['c_casa_ratio_first']:.1%}** -> **{fig['c_casa_ratio_last']:.1%}**
* Fixed-deposit balance growth over the window: **{fig['c_fd_balance_growth']:.0%}**

## d) Campaign effectiveness
* Best cost per acquired customer: **{best.campaign_name}** (BDT {best.cac:,.0f})
* High response, low conversion: **{worst.campaign_name}** (response {worst.response_rate:.1%}, conversion {worst.conversion_rate:.1%}, CAC BDT {worst.cac:,.0f})

{table}

## e) Mobile overtakes ATM
* Monthly transactions, first month: mobile {m0:,} vs ATM {a0:,}; last month: mobile {m1:,} vs ATM {a1:,}
* First month where mobile > ATM: **{first_cross.strftime('%B %Y') if first_cross is not None else 'never'}**
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-docs", action="store_true")
    args = ap.parse_args()
    t = load_all()
    print("== Data quality ==")
    failed = 0
    for name, ok, detail in quality_report(t):
        print(f"[{'PASS' if ok else 'FAIL'}] {name} {detail}")
        failed += not ok
    fig = story_figures(t)
    print("\n== Planted stories ==")
    for k, v in fig.items():
        print(f"{k}: {v}")
    if args.write_docs:
        (DOCS / "STORIES.md").write_text(render_stories(fig), encoding="utf-8")
        print("wrote docs/STORIES.md")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
